### PR TITLE
feat: upgrade webpack/eslint/mjml setup

### PR DESCRIPTION
**Pull request by DRoet**
- Bumps webpack from 3 -> 4
- adds eslint config with indent/semi rules
- updates babel to latest

~I had to disable the minimize optimization in webpack or else the same error in https://github.com/artf/grapesjs-mjml/issues/110 would occur, so I'm still looking into that~
The option `keep_fnames: true` is important to make sure the integration with `grapesjs` still works correctly, fixes https://github.com/artf/grapesjs-mjml/issues/110

**edit:**  
I took inspiration from `mjml4-in-browser` and switched our dependency back to `mjml` directly whilst still providing our own mocks so that it works in the browser

### CODE REVIEW

**Comment by DRoet** [comment]
@larsdecker @CimattiConsulting @michibat01 thoughts?

**Comment by JimmyEgberts** [comment]
Can confirm this fixes https://github.com/artf/grapesjs-mjml/issues/110 for me.

**Comment by larsdecker** [comment]
For me it looks good. 

@artf Can you please look at it?

**Comment by artf** [comment]
Thanks @DRoet for the amazing work ❤️ 
I have just one question. If we are always using `mode: "production"` how does this impact performances in development mode (webpack adds a lot of work in production mode)? Is it somehow affected right now? 
If it breaks in `development` mode somehow I'm ok with this change otherwise I'd prefer to change the mode based on the environment.

**Comment by DRoet** [comment]
@artf good call, there was indeed some performance regression in development mode since it would optimize each rerun.

I have changed it back to `development` mode and added the `-p` flag to force `production` mode in the final build

**Comment by artf** [comment]
Thanks @DRoet for your quick response, btw I'm not sure it will work in production in that way, because you're always in development right now.

For example, check how I've done it in grapesjs configuration

Dev script
https://github.com/artf/grapesjs/blob/02ceecc87dc2116435cab1c65014fab7d6a05293/package.json#L123

Build script
https://github.com/artf/grapesjs/blob/02ceecc87dc2116435cab1c65014fab7d6a05293/package.json#L116

Webpack env check
https://github.com/artf/grapesjs/blob/02ceecc87dc2116435cab1c65014fab7d6a05293/webpack.config.js#L9-L11

Webpack mode
https://github.com/artf/grapesjs/blob/02ceecc87dc2116435cab1c65014fab7d6a05293/webpack.config.js#L38

**Comment by DRoet** [comment]
@artf should be good now

**Comment by artf** [comment]
New release published https://github.com/artf/grapesjs-mjml/releases/tag/v0.1.10
Thanks again @DRoet for the effort ❤️

**Comment by kickbk** [comment]
@DRoet thanks for your incredible work.

**Comment by Felix-Indoing** [comment]
Hi, the issue occurred again in #155

**Pull request merged**
