### PR TITLE
Add webpack output to allow delayed initialization of grapesjs-mjml plugin

### PR DESCRIPTION
**Pull request by mathieuk**
In our React project, we load GrapesJS on-demand using Webpack's code splitting functionality. The current implementation of index.js makes this difficult as it immediately tries to register with grapesjs through a global variable. 

This change introduces an extra way of loading the plugin, by also providing a wrapped initialization function. This allows us to load GrapesJS like so: 

```js
  componentDidMount() {
    require.ensure([], function() { 
      var grapesjs   = require('vendor/grapes.min.js');
      var mjmlPlugin = require('vendor/grapesjs-mjml-callable.min.js');   
      mjmlPlugin.default(grapesjs);
    
      var editor = grapesjs.init({
        height: '100%',
        noticeOnUnload: 0,
        storageManager:{autoload: 0},
        fromElement: true,
        container: '#gjs',
        height: '100%',
        plugins: ['gjs-mjml'],
        pluginsOpts: {
          'gjs-mjml': {}
        }
      });
      
      return grapesjs;
    }, 'grapesjs')
  }
```

As I didn't find a way to have multiple output definitions this may break existing installations as the default output for webpack no longer is grapesjs-mjml.min.js but grapesjs-mjml-default.min.js.

### CODE REVIEW

**Comment by artf** [comment]
I don't know @mathieuk, honestly, I'd prefer to avoid breaking and overwhelming stuff just to support some third-party feature
This is how usually one would use the plugin and it works fine
https://codesandbox.io/s/p90rkzx4m7

**Comment by mathieuk** [comment]
And rightly so. I just ( :) ) realized that I can probably just code-split the entire module using GrapesJS to achieve the same goal and if not (for future reference) I can use the Webpack scriptloader to achieve the same goal. So I'm closing this PR.

**Comment by artf** [comment]
@mathieuk Great, actually I've also realized that you could do this 😬 (if I correctly got which was your problem)
```js
// The `require` of the plugin returns its plugin function
// `function(editor, config) { ...`, so...
var mjmlPlugin = require('grapesjs-mjml'); 
grapesjs.plugins.add('gjs-mjml', mjmlPlugin);
...
```

**Comment by mathieuk** [comment]
This worked fine, btw.

**Pull request closed without merging**
