### PR TITLE
Fix: Accept mj-wrapper as a droppable on mj-body

### PR DESCRIPTION
**Pull request by aroop**
Currently, the wrapper block is not draggable. This PR fixes it

### CODE REVIEW

**Comment by aroop** [comment]
Also added support for the Hero component

**Comment by aroop** [comment]
@artf When you have a moment can you please review the PR

**Comment by NorthstarTech** [comment]
@artf any update? When I will get the support of mj-hero component? 

Thanks.

**Comment by artf** [comment]
Amazing, thanks @aroop ❤️

**Pull request merged**
