### PR TITLE
fix for padding not shown correctly in style manager

### PR DESCRIPTION
**Pull request by dervagabund**
when using padding instead padding-top/left/right/bottom then the style manager is always using the padding instead of the separate property values. rendering was ok but style manager display did not work.

Should fix issue #235

### CODE REVIEW

**Comment by DRoet** [comment]
Could you please revert the `package-lock.json` changes?

**Comment by dervagabund** [comment]
should be fixed - sry

**Comment by DRoet** [comment]
hmm not sure about this change since it is a revert of https://github.com/artf/grapesjs-mjml/pull/197

**Comment by dervagabund** [comment]
true, but it does fix the the issue with the editor that it does not recognize the changed values. if the padding: 25px 10px is set, this values always overrides the padding-left/top/right/bottom values, although they are internally still correct. somehow the padding itself is shown.
maybe related: i've read somewhere (forgot the source) that if a mjml template is used, the padding-top/left/right/bottom should be used instead of the padding.
up to you - i'm using the modified version as it's working and not that confusing for the users because it's not resetting.

**Review by ThomasPof — CHANGES_REQUESTED** [review]
Missing padding left/right in `src/components/Section.js`

**Pull request merged**
